version: '3.8'

services:
  qdrant:
    image: niktor99/sc-vector-db:1.1  # Immagine preesistente
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage  # Dati persistenti
    networks:
      - analysis_network

  api_server:
    image: niktor99/api-server:latest  # Sostituisci con la tua immagine su Docker Hub
    container_name: api_server
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=qdrant:6334
      - API_ENV=production
    depends_on:
      - qdrant
    networks:
      - analysis_network

  cli_tool:
    image: niktor99/cli-base-image:latest  # Immagine pre-buildata
    container_name: cli_tool
    depends_on:
      - api_server
    networks:
      - analysis_network
    environment:
      - API_URL=http://api_server:8000
      - PYTHON=/app/src
    volumes:
      - ./tests/system_test:/app/tests/system_test  # Mount dei test di sistema
      - ./src:/app/src
    working_dir: /app
    entrypoint: [ "/bin/sh", "-c", "pip install pytest && pytest tests/system_test" ]

volumes:
  qdrant_data:
  model_cache:

networks:
  analysis_network:
    driver: bridge