version: '3.8'

services:
  qdrant:
    image: niktor99/sc-vector-db:1.1  # Immagine preesistente
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage  # Dati persistenti
    networks:
      - analysis_network

  api_server:
    image: niktor99/api-server:latest
    container_name: api_server
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant_db:6333
      - API_ENV=production
    depends_on:
      - qdrant
    networks:
      - analysis_network

  cli_tool:
    image: niktor99/cli-tool:latest
    container_name: cli_tool
    depends_on:
      - api_server
    networks:
      - analysis_network
    environment:
      - API_URL=http://api_server:8000
    volumes:
      - ./contracts:/app/contracts # Monta la cartella esterna con il codice da analizzare
      - ./output_report:/app/output_report # Monta la cartella esterna con i report delle analisi
    working_dir: /app/cli_tool
    stdin_open: true
    tty: true
    entrypoint: ["python", "cli_shell.py"]

volumes:
  qdrant_data:
  model_cache:

networks:
  analysis_network:
    driver: bridge