# Dockerfile.base
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir sentence-transformers transformers --no-deps

Run pip install --no-cache-dir huggingface_hub regex safetensors tokenizers scikit-learn

RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "from sentence_transformers import SentenceTransformer; \
     SentenceTransformer('hkunlp/instructor-large')"