name: System Test and Publish

on:
  push:
    branches: [test]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start services
        run: docker-compose -f docker-compose.system-test.yml up --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run system tests
        run: docker wait cli_tool | grep -q 0

      - name: Stop and remove containers
        if: always()
        run: docker-compose down

      - name: Build CLI Tool Docker image from src/
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cli-tool:latest ./src

      - name: Push image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cli-tool:latest


